### ISSUE TITLE
Passive vs Active ambiguity incorrect

### ISSUE THREAD

**Issue by WesleyYue** [rock-learning/pytransform3d#40]
Hi, I might be mistaken here, but it seems to me that the active vs passive matrices are flipped in the code and ambiguity documentation. Looking at the references [here](https://www.researchgate.net/profile/Bo_Lan/publication/280716878_A_Brief_Guide_to_the_Fundamentals_of_Passive_and_Active_Rotations_in_Material_Science/links/55c230fa08aeb975673e3d21/A-Brief-Guide-to-the-Fundamentals-of-Passive-and-Active-Rotations-in-Material-Science.pdf) and [here](https://docs.leggedrobotics.com/kindr/cheatsheet_latest.pdf) both suggest that a passive rotation matrix around the z axis should have a -sin() on the top right.

Am I mistaken?

**Comment by AlexanderFabisch** [comment]
Yes, I am quite confused, too.

I played around a little bit in a notebook: [link](https://gist.github.com/AlexanderFabisch/29736f4fa046c111d44ada71a0b1922e).

**Comment by AlexanderFabisch** [comment]
According to the documentation `matrix_from_angle(...)` should return a (counterclockwise) passive transformation matrix. According to the documents that you linked it should not. I rotated a couple of points and it actually looks like a passive transformation. The old coordinate system is displayed with solid lines, the new one with dashed lines. Let me know if I made a mistake.

**Comment by WesleyYue** [comment]
Let me define my variable notation by `_{frame1}_variable_{frame2}2{frame3}`, which describes the variable of frame3 with respect to frame2, described in frame1. Let's define the initial frame (solid lines) as frame A, and the second frame (dash lines) as frame B. 

 - Use `_A_pts` to describe the points created at the 4th cell (points in described in frame A).

 - Using intrinsic, pre-multiplied, source in target conventions.

If I understood correctly, mathematically, this is what you're doing in the notebook:

 1. With pr.matrix_from_angle(2, 0.5 * np.pi), I would have expected this to produce `R = _A_R_A2B`, since 0.5*pi denotes the rotation from A to B
 2. Looking at the rotation matrix output with [this reference](https://docs.leggedrobotics.com/kindr/cheatsheet_latest.pdf), it actually produces `R = _A_R_B2A`
 3.`rotate_points() = _A_pts * _A_R_A2B^T = _A_R_B2A * _A_pts` is then correct

I think the core issue for me is that with a pre-multiply convention, in order to transform a point (_A_pts) from frame A to B, I would expect that I need to implement `_B_pts = _A_R_B2A * _A_pts`, and that matrix_from_angle(theta_B2A) would produce _A_R_B2A, rather than matrix_from_angle(theta_A2B) producing _A_R_B2A.

For example, opencv's [rodrigues](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#rodrigues) function implements it the way I expect, where cv2.Rodrigues(theta_B2A) produces _B_R_B2A. I guess this is another convention thing, but it was surprising behaviour for me.

**Comment by AlexanderFabisch** [comment]
I took a second look at the [kindr cheat sheet](https://docs.leggedrobotics.com/kindr/cheatsheet_latest.pdf) and I am even more confused now. ;) There seems to be a contradiction in the definition of a passive rotation.
In the section Orientation/Rotation 3) clearly seems to represent a passive rotation since the frame in which the vector is expressed changes. However, in 2) the function `\Phi^P` is a function that maps a vector (actually is should be a set of vectors) `_I_r_O2P` to `_B_r_O2P` (I adopted your notation) and in 3) it is actually defined as a function that maps `_B_r_O2P` to `_I_r_O2P`, that is, `\Phi^P(_B_r_O2P) = C_{IB} _B_r_O2P = _I_r_O2P`. So the order seems to be inverted!? We could try to contact the authors. Maybe it is an error.

>     With pr.matrix_from_angle(2, 0.5 * np.pi), I would have expected this to produce `R = _A_R_A2B`, since 0.5*pi denotes the rotation from A to B

Yes, rotation around the z-axis by 90 degrees.

>     `rotate_points() = _A_pts * _B_R_B2A^T = _B_R_B2A * _A_pts` is then correct

This might be a bit confusing. I use the property `(A * B)^T = B^T * A^T` (see [matrix cookbook, page 6, section I Basics, equation 5](https://www.math.uwaterloo.ca/~hwolkowi/matrixcookbook.pdf)).

`_A_pts` is a matrix that contains one point in each **row**. These points are row vectors, that is, the i-th row contains a point `_A_p_i^T`. You could rotate it with `_A_R_A2B * _A_p_i = _B_p_i` or you can rotate all of the points in the matrix (using the property from above) in a single matrix-matrix multiplication: `_A_pts * _A_R_A2B^T = _B_pts` which means you apply `_A_p_i^T * _A_R_A2B^T = _B_p_i^T` to each of the points in a single operation. In summary, I use the premultiplication convention, I only use a trick to rotate all the points in one operation which needs the transposed version of the rotation matrix. Sorry for the confusion.

So I guess we have the same expectations and I currently think that the implementation and the documentation of pytransform3d are correct.

**Comment by AlexanderFabisch** [comment]
btw. here are some definitions that are consistent with pytransform3d:

* [Active versus passive rotations, Tomas Soler](https://www.researchgate.net/publication/320673731_Active_versus_Passive_Rotations)
* [Active versus passive transformations in robotics, J.M. Selig](https://openresearch.lsbu.ac.uk/download/641fa36d365e0244b27dd2fc8b881a12061afe1eb5c3952bae15614d3d831710/185181/01598057.pdf)
* [Wikipedia: Active and passive transformation](https://en.wikipedia.org/wiki/Active_and_passive_transformation)

**Comment by AlexanderFabisch** [comment]
As a reference for me, here is the definition of active and passive transformation in pytransform3d: [link](https://rock-learning.github.io/pytransform3d/transformation_ambiguities.html#active-alibi-vs-passive-alias-transformation).

**Comment by WesleyYue** [comment]
I think it makes sense to me now. The part where I was caught up was that the "conventional" rotation matrices (as implemented in eigen, opencv, kindr, etc) produce a matrix that will actively rotate a vector with the same rotation from A to B when it's left multiplied. That is, the frame of reference of the vector remains as A. To perform a passive transformation (to switch the frame of reference for the vector without moving the vector), you typically need to pass in theta from B to A, which is the same as inverting the "conventional" rotation matrix.

So I agree the implementation and documentation in pytransform3d is indeed correct and internally consistent. It is just opposite of the behaviour of similar functions in other libraries as the other libraries return a rotation matrix as an active transformation matrix by default.

> In the section Orientation/Rotation 3) clearly seems to represent a passive rotation since the frame in which the vector is expressed changes. However, in 2) the function \Phi^P is a function that maps a vector (actually is should be a set of vectors) _I_r_O2P to _B_r_O2P (I adopted your notation) and in 3) it is actually defined as a function that maps _B_r_O2P to _I_r_O2P, that is, \Phi^P(_B_r_O2P) = C_{IB} _B_r_O2P = _I_r_O2P. So the order seems to be inverted!? We could try to contact the authors. Maybe it is an error.

I think this is fine since they never explicitly stated `\Phi^P(x) = C_{IB} x`. Though I agree it would have made it less confusing if they actually provided an example of transforming the vector from I to B instead of B to I after immediately showing an example of a passive rotation from I to B.

**Comment by WesleyYue** [comment]
My understanding on the ambiguities of transformation notation has improved greatly from this. Thanks for the discussion!

**Comment by AlexanderFabisch** [comment]
Thanks. I think I will link to this discussion in the documentation. Could you elaborate a bit more in the behavior of opencv or eigen? They are quite stabdard libraries so it would at least make sense to mention the differences.

**Comment by WesleyYue** [comment]
Building off of your example: https://gist.github.com/WesleyYue/b268038fe5c61a3833950f4c482d1596

**Comment by theRealSuperMario** [comment]
The https://github.com/matthew-brett/transforms3d package has a very nice explanation of active ("r") vs passive ("s") rotations, more specifically for the euler angle convention. One could think about just switching all the functionality so that is uses the `transforms3d` library, which is by > 200 projects and therefore pretty well tested

https://github.com/matthew-brett/transforms3d
