### ISSUE TITLE
Dynamically remove TransformationManager's nodes.

### ISSUE THREAD

**Issue by dtransposed** [rock-learning/pytransform3d#81]
Hello!

Thank you for this great library!

I wonder if there is some simple way to remove nodes from Transformation Manager. I have a fairly complicated transformation chain. I keep adding new nodes on the fly and the graph gets ridiculously slow. I think that it would help me if I could remove the old nodes. Is it currently possible?

Cheers!

**Comment by AlexanderFabisch** [comment]
Hi.

> Thank you for this great library!

Thanks, that's good to read. :)

> I wonder if there is some simple way to remove nodes from Transformation Manager.

Do you really want to remove nodes or do you want to remove transformations? Because removing nodes would probably be the more expensive operation.

No, there is currently no function `remove_node` or `remove_transform` although it should be quite easy to implement at least `remove_transform`. I am currently just implementing the features that I need for my work or features requested by users of the library. These functions didn't seem to be necessary so far. :D If you want to contribute something to the library I could give you some hints for the implementation.

> I have a fairly complicated transformation chain. I keep adding new nodes on the fly and the graph gets ridiculously slow.

So about how many nodes / transformations are we talking here? Did you try to run a profiler to identify the bottlenecks? (`python -m cProfile -s cumtime script.py > profile.txt`)

Which version of pytransform3d are you using? I recently made the code a lot faster (about 10x in my use case) so that I can even visualize full humanoid robots quite fast. Unfortunately, some performance comes at the cost of turning off safety checks in the constructor with `TransformManager(check=False)` (which should be OK when the code was tested previously).

However, I also explicitly decided against some speed hacks (like caching of transformation chains) because I want to keep the implementation simple.

**Comment by dtransposed** [comment]
> Do you really want to remove nodes or do you want to remove transformations? Because removing nodes would probably be the more expensive operation.

For some problems just removing transformations suffices. By removing a transformation I understand keeping the graph intact while "overwriting" the transformation matrix in `tm.transforms` dictionary. For this particular problem described, removing a transformation is not the appropriate solution.

> Did you try to run a profiler to identify the bottlenecks? 

Thank you for that advice. The profiler has revealed, that my speed problem has a completely different source from what I have initially expected.
I have been, by mistake, calling the `check consistency` method at every execution step. This has been the reason for the sluggish execution.

Thank you for your help!

Keep on with the great work!

**Comment by AlexanderFabisch** [comment]
I'll leave the issue open since the function `remove_transform` should actually be part of TransformManager.

> By removing a transformation I understand keeping the graph intact while "overwriting" the transformation matrix in tm.transforms dictionary.

No, no, that is what `add_transform` does anyway, right?

`remove_transform` would delete the transformation from the dict `transforms`:

https://github.com/rock-learning/pytransform3d/blob/master/pytransform3d/transform_manager.py#L52-L63

This would require recomputation of the shortest path matrix.

Removing a node would also require reassigning indices to all other nodes. In comparison to O[N(N*k + N*log(N))] of Dijkstra it is not much, but it is still O[N].
